spring.application.name=learn-spring-boot
logging.level.org.springframework=debug

spring.profiles.active=dev

currency-service.url=https://babrakov.win
currency-service.username=default-user
currency-service.key=default-key

management.endpoints.web.exposure.include=*